### ISSUE TITLE
OSError: PdhAddCounterW failed: PDH_CSTATUS_NO_OBJECT

### ISSUE THREAD

**Issue by isonwillis** [mixmastamyk/winstats#5]
python.exe -m winstats
Memory Stats:
....\winstats.py:358: DeprecationWarning: This method will be removed in a future version of Python. Use 'locale.format_string()' instead.
./
PerfMon queries:
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File ...\winstats.py", line 388, in <module>
    usage = get_perf_data(r'\Processor(_Total)\% Processor Time',
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ...\Lib\site-packages\winstats.py", line 316, in get_perf_data
    raise WindowsError('PdhAddCounterW failed: %s' % get_pd_err(errs))
OSError: PdhAddCounterW failed: PDH_CSTATUS_NO_OBJECT

**Comment by mixmastamyk** [comment]
I haven't used windows regularly in years.  If you'd like to make a pull request to fix it, I'd accept it.
